export default class ClientProt {
    // TODO: remove removed packets + get value id
    static readonly NO_TIMEOUT: number = 0; // value: 6 - NXT naming
    static readonly FOCUS_CHANGE: number = 3; // value: 25
    static readonly IDLE_TIMER: number = 202; // value: 30
    static readonly MOUSE_CLICK: number = 241; // value: 31
    static readonly ACCOUNT_FLAGGED: number = 45; // value: 32
    static readonly REGION_CHANGE: number = 210; // value: 36

    // TODO: mouserecorder instead of anticheats
    // autogenerated as part of obfuscation process
    static readonly ANTICHEAT_OPLOGIC1: number = 200; // value: 60
    static readonly ANTICHEAT_OPLOGIC2: number = 152; // value: 61
    static readonly ANTICHEAT_OPLOGIC3: number = 189; // value: 62
    static readonly ANTICHEAT_OPLOGIC4: number = 36; // value: 63
    static readonly ANTICHEAT_OPLOGIC5: number = 183; // value: 64
    static readonly ANTICHEAT_OPLOGIC6: number = 136; // value: 65
    static readonly ANTICHEAT_OPLOGIC7: number = 85; // value: 66
    static readonly ANTICHEAT_OPLOGIC8: number = 230; // value: 67
    static readonly ANTICHEAT_OPLOGIC9: number = 255; // value: 68

    // autogenerated as part of obfuscation process
    static readonly ANTICHEAT_CYCLELOGIC1: number = 226; // value: 70
    static readonly ANTICHEAT_CYCLELOGIC2: number = 238; // value: 71
    static readonly ANTICHEAT_CYCLELOGIC3: number = 78; // value: 74
    static readonly ANTICHEAT_CYCLELOGIC4: number = 150; // value: 72
    static readonly ANTICHEAT_CYCLELOGIC5: number = 165; // value: 75
    static readonly ANTICHEAT_CYCLELOGIC6: number = 246; // value: 73

    static readonly OPOBJ1: number = 156; // value: 80 - NXT naming
    static readonly OPOBJ2: number = 23; // value: 81 - NXT naming
    static readonly OPOBJ3: number = 236; // value: 82 - NXT naming
    static readonly OPOBJ4: number = 253; // value: 83 - NXT naming
    static readonly OPOBJ5: number = 79; // value: 84 - NXT naming
    static readonly OPOBJT: number = 181; // value: 88 - NXT naming
    static readonly OPOBJU: number = 25; // value: 89 - NXT naming

    static readonly OPNPC1: number = 155; // value: 100 - NXT naming
    static readonly OPNPC2: number = 72; // value: 101 - NXT naming
    static readonly OPNPC3: number = 17; // value: 102 - NXT naming
    static readonly OPNPC4: number = 21; // value: 103 - NXT naming
    static readonly OPNPC5: number = 18; // value: 104 - NXT naming
    static readonly OPNPCT: number = 131; // value: 108 - NXT naming
    static readonly OPNPCU: number = 57; // value: 109 - NXT naming

    static readonly OPLOC1: number = 132; // value: 120 - NXT naming
    static readonly OPLOC2: number = 252; // value: 121 - NXT naming
    static readonly OPLOC3: number = 70; // value: 122 - NXT naming
    static readonly OPLOC4: number = 234; // value: 123 - NXT naming
    static readonly OPLOC5: number = 228; // value: 124 - NXT naming
    static readonly OPLOCT: number = 35; // value: 128 - NXT naming
    static readonly OPLOCU: number = 192; // value: 129 - NXT naming

    static readonly OPPLAYER1: number = 128; // value: 140 - NXT naming
    static readonly OPPLAYER2: number = 153; // value: 141 - NXT naming
    static readonly OPPLAYER3: number = 73; // value: 142 - NXT naming
    static readonly OPPLAYER4: number = 139; // value: 143 - NXT naming
    static readonly OPPLAYER5: number = 39; // value: 144 - NXT naming
    static readonly OPPLAYERT: number = 249; // value: 148 - NXT naming
    static readonly OPPLAYERU: number = 14; // value: 149 - NXT naming

    static readonly OPHELD1: number = 122; // value: 160 - name based on runescript trigger
    static readonly OPHELD2: number = 41; // value: 161 - name based on runescript trigger
    static readonly OPHELD3: number = 16; // value: 162 - name based on runescript trigger
    static readonly OPHELD4: number = 75; // value: 163 - name based on runescript trigger
    static readonly OPHELD5: number = 87; // value: 164 - name based on runescript trigger
    static readonly OPHELDT: number = 237; // value: 168 - name based on runescript trigger
    static readonly OPHELDU: number = 53; // value: 169 - name based on runescript trigger

    static readonly INV_BUTTON1: number = 145; // value: 190 - NXT has "IF_BUTTON1" but for our interface system; this makes more sense
    static readonly INV_BUTTON2: number = 117; // value: 191 - NXT has "IF_BUTTON2" but for our interface system; this makes more sense
    static readonly INV_BUTTON3: number = 43; // value: 192 - NXT has "IF_BUTTON3" but for our interface system; this makes more sense
    static readonly INV_BUTTON4: number = 129; // value: 193 - NXT has "IF_BUTTON4" but for our interface system; this makes more sense
    static readonly INV_BUTTON5: number = 135; // value: 194 - NXT has "IF_BUTTON5" but for our interface system; this makes more sense
    static readonly IF_BUTTON: number = 185; // value: 200 - NXT naming

    static readonly RESUME_PAUSEBUTTON: number = 40; // value: 201 - NXT naming
    static readonly CLOSE_MODAL: number = 130; // value: 202 - NXT naming
    static readonly RESUME_P_COUNTDIALOG: number = 208; // value: 203 - NXT naming
    static readonly TUTORIAL_CLICKSIDE: number = 120; // value: 204
    static readonly INTERFACE_TYPING: number = 60; // value: 205

    static readonly LOADING_FINISHED: number = 121; // value: 241
    static readonly MOVE_OPCLICK: number = 98; // value: 242 - comes with OP packets; name based on other MOVE packets
    static readonly BUG_REPORT: number = 218; // value: 243 - NXT naming
    static readonly MOVE_MINIMAPCLICK: number = 248; // value: 244 - NXT naming
    static readonly INV_BUTTOND: number = 214; // value: 245 - NXT has "IF_BUTTOND" but for our interface system; this makes more sense
    static readonly IGNORELIST_DEL: number = 74; // value: 246 - NXT naming
    static readonly IGNORELIST_ADD: number = 133; // value: 247 - NXT naming
    static readonly IF_PLAYERDESIGN: number = 101; // value: 248
    static readonly CHAT_SETMODE: number = 95; // value: 249 - NXT naming
    static readonly MESSAGE_PRIVATE: number = 126; // value: 250 - NXT naming
    static readonly FRIENDLIST_DEL: number = 215; // value: 251 - NXT naming
    static readonly FRIENDLIST_ADD: number = 188; // value: 252 - NXT naming
    static readonly CLIENT_CHEAT: number = 103; // value: 253 - NXT naming
    static readonly MESSAGE_PUBLIC: number = 4; // value: 254 - NXT naming
    static readonly MOVE_GAMECLICK: number = 164; // value: 255 - NXT naming
}
